
#pragma once

typedef
HRESULT
(APIENTRY *IDIRECTINPUTDEVICE8A_GETDEVICEDATA)(
	IN LPDIRECTINPUTDEVICE8A This,
	IN DWORD cbObjectData,
	IN LPDIDEVICEOBJECTDATA rgdod,
	OUT LPDWORD pdwInOut,
	IN DWORD dwFlags);

typedef
HRESULT
(APIENTRY *IDIRECTINPUTDEVICE8A_GETDEVICESTATE)(
	IN LPDIRECTINPUTDEVICE8A This,
	IN DWORD cbData,
	OUT LPVOID lpvData);

typedef
HRESULT
(APIENTRY *IDIRECTINPUTDEVICE8W_GETDEVICEDATA)(
	IN LPDIRECTINPUTDEVICE8W This,
	IN DWORD cbObjectData,
	IN LPDIDEVICEOBJECTDATA rgdod,
	OUT LPDWORD pdwInOut,
	IN DWORD dwFlags);

typedef
HRESULT
(APIENTRY *IDIRECTINPUTDEVICE8W_GETDEVICESTATE)(
	IN LPDIRECTINPUTDEVICE8W This,
	IN DWORD cbData,
	OUT LPVOID lpvData);


extern volatile IDirectInputDevice8AVtbl *DIHook_IDirectInputDevice8A_Vtbl;
extern volatile IDirectInputDevice8WVtbl *DIHook_IDirectInputDevice8W_Vtbl;

extern volatile IDIRECTINPUTDEVICE8A_GETDEVICEDATA DIHook_IDirectInputDevice8A_GetDeviceData_Previous;
extern volatile IDIRECTINPUTDEVICE8A_GETDEVICESTATE DIHook_IDirectInputDevice8A_GetDeviceState_Previous;
extern volatile IDIRECTINPUTDEVICE8W_GETDEVICEDATA DIHook_IDirectInputDevice8W_GetDeviceData_Previous;
extern volatile IDIRECTINPUTDEVICE8W_GETDEVICESTATE DIHook_IDirectInputDevice8W_GetDeviceState_Previous;


HRESULT
APIENTRY
DIHook_IDirectInputDevice8A_GetDeviceData(
	IN LPDIRECTINPUTDEVICE8A This,
	IN DWORD cbObjectData,
	IN LPDIDEVICEOBJECTDATA rgdod,
	OUT LPDWORD pdwInOut,
	IN DWORD dwFlags);

HRESULT
APIENTRY
DIHook_IDirectInputDevice8W_GetDeviceData(
	IN LPDIRECTINPUTDEVICE8W This,
	IN DWORD cbObjectData,
	IN LPDIDEVICEOBJECTDATA rgdod,
	OUT LPDWORD pdwInOut,
	IN DWORD dwFlags);

HRESULT
APIENTRY
DIHook_IDirectInputDevice8A_GetDeviceState(
	IN LPDIRECTINPUTDEVICE8A This,
	IN DWORD cbData,
	OUT LPVOID lpvData);

HRESULT
APIENTRY
DIHook_IDirectInputDevice8W_GetDeviceState(
	IN LPDIRECTINPUTDEVICE8W This,
	IN DWORD cbData,
	OUT LPVOID lpvData);


BOOL
InstallHook(
	VOID);

BOOL
UninstallHook(
	VOID);

